# Generated by Django 5.1.3 on 2025-01-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_remove_rdv_first_name_remove_rdv_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='fiche_patient',
            new_name='patient',
        ),
    ]
