# Generated by Django 5.1.3 on 2025-01-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_rename_fiche_patient_consultation_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='Traitement',
            new_name='Ordonnance',
        ),
    ]
