# Generated by Django 5.1.3 on 2025-01-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_rename_traitement_consultation_ordonnance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabinetDentaire',
        ),
    ]
