# Generated by Django 5.1.3 on 2025-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_delete_cabinetdentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='fiche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
