# Generated by Django 5.1.3 on 2025-01-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_alter_rdv_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdv',
            options={},
        ),
    ]
